// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "tutorial" }],
  docsSidebar: [
    {
      type: "category",
      label: "The editor",
      link: { type: 'doc', id: 'documentation/editor/index-editor' },
      items: [
        {
          type: 'category',
          label: 'Card types',
          items: [{ type: "autogenerated", dirName: "documentation/cards" }],
        },
      ],
    },
    {
      type: "category",
      label: "Accounts & Structure",
      items: [{ type: "autogenerated", dirName: "documentation/dashboard" }],
    },
    {
      type: "category",
      label: "General",
      items: [{ type: "autogenerated", dirName: "documentation/general" }],
    },
    {
      type: "category",
      label: "Portfolio",
      items: [{ type: "autogenerated", dirName: "documentation/portfolio" }],
    },
  ],
};

export default sidebars;
