// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "tutorial" }],
  docsSidebar: [
    {
      type: "category",
      label: "Journey building blocks",
      link: { type: "doc", id: "documentation/editor/index-editor" },
      items: [
        {
          type: "category",
          label: "Cards",
          items: [{ type: "autogenerated", dirName: "documentation/cards" }],
        },
        {
          type: "category",
          label: "Lanes",
          items: [
            {
              type: "category",
              label: "Simple lanes",
              items: [
                {
                  type: "link",
                  label: "Stage",
                  href: "??",
                },
                {
                  type: "link",
                  label: "Text",
                  href: "??",
                },
                {
                  type: "link",
                  label: "Image",
                  href: "??",
                },
         
                {
                  type: "link",
                  label: "Linked Maps",
                  href: "??",
                },
                {
                  type: "link",
                  label: "Opportunity",
                  href: "??",
                },
                {
                  type: "link",
                  label: "Painpoint",
                  href: "??",
                },
                {
                  type: "link",
                  label: "Solution",
                  href: "??",
                },
              ],
            },
            {
              type: "link",
              label: "Grid lane",
              href: "??",
            },
            {
              type: "link",
              label: "Emotional chart lane",
              href: "??",
            },
          ],
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Accounts & Structure",
    //   items: [{ type: "autogenerated", dirName: "documentation/dashboard" }],
    // },
    // {
    //   type: "category",
    //   label: "General",
    //   items: [{ type: "autogenerated", dirName: "documentation/general" }],
    // },
    // {
    //   type: "category",
    //   label: "Portfolio",
    //   items: [{ type: "autogenerated", dirName: "documentation/portfolio" }],
    // },
  ],
};

export default sidebars;
