// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "tutorial" }],
  docsSidebar: [
    {
      type: "category",
      label: "Metrics",
      items: [
        {
          type: "doc",
          label: "Introduction to Metrics",
          id: "documentation/metrics/get-started",
        },
        {
          type: "doc",
          label: "Types of Metrics",
          id: "documentation/metrics/types-of-metrics",
        },{
          type: "category",
          label: "Google Analytics",
          items: [{ type: "autogenerated", dirName: "documentation/metrics/integrations/google-analytics" }],
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Accounts & Structure",
    //   items: [{ type: "autogenerated", dirName: "documentation/dashboard" }],
    // },
    // {
    //   type: "category",
    //   label: "General",
    //   items: [{ type: "autogenerated", dirName: "documentation/general" }],
    // },
    // {
    //   type: "category",
    //   label: "Portfolio",
    //   items: [{ type: "autogenerated", dirName: "documentation/portfolio" }],
    // },
  ],
};

export default sidebars;
